global_exclude_dirs:
    - vendor
    - bin
    - ansible
    - spec

exclude_patterns:
    - app/check.php
    - app/SymfonyRequirements.php
    - web/config.php
    - web/app_*.php
    - app/Resource/public/*